theme: jekyll-theme-minimal
title: Mi Blog
description: Bienvenido a mi blog
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
defaults:
  - scope:
      path: ""
    values:
      layout: home
